// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {NodeProp} from "lezer"
export const parser = Parser.deserialize({
  states: "$UQPOPOOOdOPO'#CfOzOPO'#CkOOOO'#C^'#C^O!UOQO'#CpOOOO'#C`'#C`OOOO'#Cj'#CjO!cOSO'#CjOOOO(3@u(3@uQOOOOOOOOO,58},58}O!gOPO'#CgOOOO(3@v(3@vOOOO,59V,59VO!qOPO,59VO!uOQO'#ChOOOO(3@w(3@wOOOO,59[,59[O#SOPO,59[OOOO,59U,59UOOOO,59O,59OOOOO1G.q1G.qOOOO,59P,59POOOO1G.v1G.v",
  stateData: "#W~RVOTTOUUO`QOaUOeSO~RVOTTOUUO`QOaUOeSO]YX~`QOa[Ob]O~TTOeSOf`OgaO~ccO~`QOa[ObZX~beO~TTOeSOf`Og[X~ggO~",
  goto: "!qePPfPjPPrx!O!U!X![P!_!cPPPP!kTUOPSUOPT`S_QPORYPQZQRdZQ_SRf_RXOR^QRbSTWOPSROPT[QZXTOPS_",
  nodeNames: "⚠ AgdaProgram BlockComment LineComment Hole ? String",
  maxTerm: 23,
  nodeProps: [
    [NodeProp.top, 1,true]
  ],
  repeatNodeCount: 3,
  tokenData: "(_~R^OY}YZ#PZq}qr#lrs%bsw}wx&ox}}}!O&t!O!a}!a!b'j!b#o}#o#p'o#p~}R!UUfQaPOq!hsw!hx}!h!O!a!h!b#o!h#p~!hP!mUaPOq!hsw!hx}!h!O!a!h!b#o!h#p~!hV#YUfQcSaPOq!hsw!hx}!h!O!a!h!b#o!h#p~!h~#qRfQO#q#z#q#r%]#r~#zP#}XOq!hqr$jsw!hx}!h}!O$s!O!a!h!b#o!h#o#p%P#p~!hP$mQO#q#z#r~#zP$vRO}#z!O#q#z#r~#zP%SROq#zr}#z!O~#z~%bOg~R%iUUPfQOY%{Zr%{rs&ds#O%{#O#P&i#P~%{P&QUUPOY%{Zr%{rs&ds#O%{#O#P&i#P~%{P&iOUPP&lPO~%{Q&tOfQR&yTfQO}#z}!O'Y!O#q#z#q#r'e#r~#zP'_QRPOY'YZ~'YP'jObP~'oOT~~'tTfQOq#zqr(Tr}#z}!O(Y!O~#z~(YOe~P(_O`P",
  tokenizers: [0, 1, 2],
  topRules: {"AgdaProgram":[0,1]},
  tokenPrec: 0
})
